[package]
name = "ascom-alpaca-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.5.16", features = ["headers"] }
form_urlencoded = "1.1.0"
mime = "0.3.16"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
serde_plain = "1.0.0"
serde_repr = "0.1.9"
serde_urlencoded = "0.7.1"
tracing = "0.1.37"
