[package]
name = "ascom-alpaca-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
async-stream = "0.3.3"
async-trait = "0.1.64"
auto_enums = { version = "0.7.12", features = ["serde"] }
axum = { version = "0.5.16", features = ["headers"] }
bytemuck = { version = "1.13.0", features = ["derive", "extern_crate_std"] }
form_urlencoded = "1.1.0"
futures = "0.3.26"
indexmap = { version = "1.9.2", features = ["serde"] }
mediatype = "0.19.11"
mime = "0.3.16"
ndarray = "0.15.6"
serde = { version = "1.0.145", features = ["derive"] }
serde_iter = "0.1.1"
serde_json = "1.0.86"
serde_repr = "0.1.9"
serde_urlencoded = "0.7.1"
thiserror = "1.0.37"
tokio = "1.25.0"
tracing = "0.1.37"
