[package]
name = "ascom-alpaca"
version = "1.0.0-beta.1"
edition = "2021"
authors = ["Ingvar Stepanyan <me@rreverser.com>"]
categories = ["api-bindings", "science", "hardware-support"]
keywords = ["ascom", "alpaca", "astronomy", "astrophotography"]
description = "Rust implementation of the ASCOM Alpaca API for astronomy devices"
repository = "https://github.com/RReverser/ascom-alpaca-rs"
license = "MIT OR Apache-2.0"

[dependencies]
async-fn-stream = "0.2.0"
async-trait = "0.1.77"
axum = { version = "0.7.4", optional = true }
bytemuck = { version = "1.14.0", features = ["derive", "extern_crate_std"], optional = true }
bytes = { version = "1.5.0", optional = true }
custom_debug = "0.5.1"
default-net = "0.21.0"
eyre = "0.6.11"
futures = "0.3.30"
http = "1.0.0"
indexmap = { version = "2.1.0", features = ["serde"] }
macro_rules_attribute = "0.2.0"
mediatype = { version = "0.19.17", optional = true }
mime = { version = "0.3.17", optional = true }
ndarray = { version = "0.15.6", optional = true }
net-literals = "0.2.0"
num_enum = "0.7.2"
once_cell = { version = "1.19.0", optional = true }
rand = { version = "0.8.5", optional = true }
reqwest = { version = "0.11.23", optional = true, default-features = false, features = ["json"] }
sailfish = { version = "0.8.3", optional = true }
serde = { version = "1.0.195", features = ["derive", "rc"] }
serde-ndim = { version = "1.1.0", optional = true, features = ["ndarray"] }
serde_json = { version = "1.0.111" }
serde_plain = "1.0.2"
serde_repr = "0.1.18"
socket2 = "0.5.5"
thiserror = "1.0.56"
time = { version = "0.3.31", features = ["formatting", "parsing", "macros"] }
tokio = { version = "1.35.1", features = ["net", "rt"] }
tracing = "0.1.40"
tracing-futures = { version = "0.2.5", features = ["futures-03"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52.0", features = ["Win32_Networking_WinSock", "Win32_Foundation", "Win32_System_IO"] }

[dev-dependencies]
ascom-alpaca = { path = ".", features = ["test"] }
bayer = "0.1.5"
criterion = { version = "0.5.1", features = ["async_tokio"] }
ctor = "0.2.6"
eframe = "0.25.0"
# apparently Cargo doesn't allow `test` to enable `ndarray/rayon` when `ndarray` is an optional dependency
# hence the duplicate dep with rayon feature
ndarray = { version = "0.15.6", features = ["rayon"] }
nokhwa = { version = "0.10.4", features = ["input-native", "output-threaded"] }
parking_lot = { version = "0.12.1", features = ["arc_lock", "send_guard"] }
serial_test = "3.0.0"
time = { version = "0.3.31", features = ["formatting"] }
tracing-subscriber = "0.3.18"
tracing-error = "0.2.0"
color-eyre = "0.6.2"
tracing-forest = { version = "0.1.6", features = ["ansi"] }

[[bench]]
name = "image_array"
harness = false

[features]
all-devices = ["camera", "covercalibrator", "dome", "filterwheel", "focuser", "observingconditions", "rotator", "safetymonitor", "switch", "telescope"]

camera = ["dep:mediatype", "dep:bytemuck", "dep:ndarray", "dep:serde-ndim"]
covercalibrator = []
dome = []
filterwheel = []
focuser = []
observingconditions = []
rotator = []
safetymonitor = []
switch = []
telescope = []

client = ["dep:reqwest", "dep:bytes", "dep:mime", "dep:rand", "dep:once_cell"]
server = ["dep:axum", "dep:sailfish", "tokio/macros"]

test = ["client", "server", "camera", "tokio/macros", "tokio/rt-multi-thread"]

nightly = []

[package.metadata.docs.rs]
all-features = true
