[package]
name = "ascom-alpaca-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-utils = { version = "3.0.0", optional = true }
actix-web = { version = "4.2.1", optional = true }
form_urlencoded = "1.1.0"
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
serde_repr = "0.1.9"
serde_urlencoded = "0.7.1"
tracing = "0.1.37"

[features]
actix = ["actix-web", "actix-utils"]
