[package]
name = "ascom-alpaca-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
async-stream = "0.3.3"
async-trait = "0.1.64"
auto_enums = { version = "0.8.0", features = ["serde"] }
axum = { version = "0.6.11", features = ["headers"] }
bytemuck = { version = "1.13.0", features = ["derive", "extern_crate_std"] }
bytes = "1.4.0"
futures = "0.3.26"
indexmap = { version = "1.9.2", features = ["serde"] }
mediatype = "0.19.11"
mime = "0.3.16"
ndarray = "0.15.6"
net-literals = "0.2.0"
num_enum = "0.5.9"
rand = "0.8.5"
reqwest = { version = "0.11.14", default-features = false, features = ["json"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_iter = "0.1.1"
serde_json = "1.0.86"
serde_repr = "0.1.9"
thiserror = "1.0.37"
tokio = { version = "1.25.0", features = ["macros"] }
tracing = "0.1.37"

[dev-dependencies]
tokio = { version = "1.25.0", features = ["rt-multi-thread"] }

[features]
all-devices = [
	"camera",
	"covercalibrator",
	"dome",
	"filterwheel",
	"focuser",
	"observingconditions",
	"rotator",
	"safetymonitor",
	"switch",
	"telescope",
]
camera = []
covercalibrator = []
dome = []
filterwheel = []
focuser = []
observingconditions = []
rotator = []
safetymonitor = []
switch = []
telescope = []

nightly = []

[package.metadata.docs.rs]
all-features = true
