[package]
name = "ascom-alpaca"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.68"
async-stream = "0.3.3"
async-trait = "0.1.64"
axum = { version = "0.6.11", optional = true, features = ["headers"] }
bytemuck = { version = "1.13.0", features = ["derive", "extern_crate_std"], optional = true }
bytes = { version = "1.4.0", optional = true }
custom_debug = "0.5.1"
futures = "0.3.26"
indexmap = { version = "1.9.2", features = ["serde"] }
macro_rules_attribute = "0.1.3"
mediatype = { version = "0.19.11", optional = true }
mime = { version = "0.3.16", optional = true }
ndarray = { version = "0.15.6", optional = true }
net-literals = "0.2.0"
num_enum = "0.5.9"
rand = { version = "0.8.5", optional = true }
reqwest = { version = "0.11.14", optional = true, default-features = false, features = ["json"] }
serde = { version = "1.0.145", features = ["derive", "rc"] }
serde-ndim = { version = "1.0.0", optional = true, features = ["ndarray"] }
serde_json = { version = "1.0.86" }
serde_repr = "0.1.9"
socket2 = "0.5.1"
thiserror = "1.0.37"
tokio = { version = "1.25.0", features = ["net"] }
tracing = "0.1.37"

[dev-dependencies]
ascom-alpaca = { path = ".", features = ["test"] }
bayer = "0.1.5"
criterion = { version = "0.4.0", features = ["async_tokio"] }
eframe = "0.21.3"
image = { version = "0.24.6", default-features = false }
nokhwa = { version = "0.10.3", features = ["input-native", "output-threaded"] }
parking_lot = "0.12.1"
time = { version = "0.3.20", features = ["formatting"] }
tracing-subscriber = "0.3.16"

[[bench]]
name = "image_array"
harness = false

[features]
all-devices = ["camera", "covercalibrator", "dome", "filterwheel", "focuser", "observingconditions", "rotator", "safetymonitor", "switch", "telescope"]

camera = ["dep:mediatype", "dep:bytemuck", "dep:ndarray", "dep:serde-ndim"]
covercalibrator = []
dome = []
filterwheel = []
focuser = []
observingconditions = []
rotator = []
safetymonitor = []
switch = []
telescope = []

client = ["dep:reqwest", "dep:bytes", "dep:mime", "dep:rand"]
server = ["dep:axum", "tokio/macros"]

test = ["client", "server", "camera", "anyhow/backtrace", "tokio/macros", "tokio/rt-multi-thread"]

nightly = []

[package.metadata.docs.rs]
all-features = true
