name: Rust

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  clippy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        network: [client, server]
        # Camera and telescope have some special logic; other devices don't so we pick focuser as a random representative.
        device: [camera, telescope, focuser]
        include:
          # Also make sure that maximum configuration works as expected.
          - network: client,server
            device: all-devices

    steps:
      - uses: actions/checkout@v4
      - name: Clippy check
        run: cargo clippy --all --all-targets --features ${{ matrix.network }},${{ matrix.device }}
